//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspectionPractice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InspectionEntities : DbContext
    {
        public InspectionEntities()
            : base("name=InspectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<EngineType> EngineType { get; set; }
        public virtual DbSet<License> License { get; set; }
        public virtual DbSet<LicenseCategory> LicenseCategory { get; set; }
        public virtual DbSet<LicenseState> LicenseState { get; set; }
        public virtual DbSet<PhotoOfVehicleAccident> PhotoOfVehicleAccident { get; set; }
        public virtual DbSet<TypeOfDrive> TypeOfDrive { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<VehicleAccident> VehicleAccident { get; set; }
        public virtual DbSet<VehicleColor> VehicleColor { get; set; }
        public virtual DbSet<VehicleManufacturer> VehicleManufacturer { get; set; }
        public virtual DbSet<VehicleModel> VehicleModel { get; set; }
    }
}
